using System.Runtime.InteropServices;
using Fgvm.Environment;
using Fgvm.Types;
using Microsoft.Extensions.Logging.Abstractions;

namespace Fgvm.Tests.EndToEnd;

public sealed class HostSystemArtifactTests : IDisposable
{
    private readonly string _rootPath = Path.Combine(Path.GetTempPath(), "fgvm-host-system-tests", Guid.NewGuid().ToString("N"));

    public void Dispose()
    {
        if (Directory.Exists(_rootPath))
        {
            Directory.Delete(_rootPath, true);
        }
    }

    [Fact]
    public void EnsureShim_WritesUnixShim()
    {
        var hostSystem = CreateHostSystem(OS.Linux);

        var result = hostSystem.EnsureShim("/opt/fgvm/fgvm");

        Assert.IsType<Result<Unit, ShimError>.Success>(result);
        var shimPath = Path.Combine(_rootPath, "bin", "godot");
        Assert.True(File.Exists(shimPath));
        Assert.Equal(
            $"#!/usr/bin/env sh{System.Environment.NewLine}# Generated by fgvm. Do not edit.{System.Environment.NewLine}if [ \"$#\" -eq 0 ]; then{System.Environment.NewLine}  exec \"/opt/fgvm/fgvm\" godot{System.Environment.NewLine}else{System.Environment.NewLine}  exec \"/opt/fgvm/fgvm\" godot --args \"$*\"{System.Environment.NewLine}fi{System.Environment.NewLine}",
            File.ReadAllText(shimPath));

        if (!OperatingSystem.IsWindows())
        {
            Assert.True(File.GetUnixFileMode(shimPath).HasFlag(UnixFileMode.UserExecute));
        }
    }

    [Fact]
    public void EnsureShim_WritesWindowsShim()
    {
        var hostSystem = CreateHostSystem(OS.Windows);

        var result = hostSystem.EnsureShim(@"C:\fgvm\fgvm.exe");

        Assert.IsType<Result<Unit, ShimError>.Success>(result);
        var shimPath = Path.Combine(_rootPath, "bin", "godot.cmd");
        Assert.True(File.Exists(shimPath));
        Assert.Equal(
            $"@echo off{System.Environment.NewLine}REM Generated by fgvm. Do not edit.{System.Environment.NewLine}if \"%~1\"==\"\" ({System.Environment.NewLine}  \"C:\\fgvm\\fgvm.exe\" godot{System.Environment.NewLine}) else ({System.Environment.NewLine}  \"C:\\fgvm\\fgvm.exe\" godot --args \"%*\"{System.Environment.NewLine}){System.Environment.NewLine}exit /b %ERRORLEVEL%{System.Environment.NewLine}",
            File.ReadAllText(shimPath));
    }

    [Fact]
    public void EnsureShim_ReplacesOldBinGodotSymlink()
    {
        if (OperatingSystem.IsWindows())
        {
            return;
        }

        Directory.CreateDirectory(Path.Combine(_rootPath, "bin"));
        var targetPath = Path.Combine(_rootPath, "selected-godot");
        File.WriteAllText(targetPath, "");
        File.CreateSymbolicLink(Path.Combine(_rootPath, "bin", "godot"), targetPath);
        var hostSystem = CreateHostSystem(OS.Linux);

        var result = hostSystem.EnsureShim("/opt/fgvm/fgvm");

        Assert.IsType<Result<Unit, ShimError>.Success>(result);
        var shim = new FileInfo(Path.Combine(_rootPath, "bin", "godot"));
        Assert.Null(shim.LinkTarget);
        Assert.Contains("Generated by fgvm", File.ReadAllText(shim.FullName));
    }

    [Fact]
    public void EnsureShim_DoesNotOverwriteUserFile()
    {
        Directory.CreateDirectory(Path.Combine(_rootPath, "bin"));
        var shimPath = Path.Combine(_rootPath, "bin", "godot");
        File.WriteAllText(shimPath, "user script");
        var hostSystem = CreateHostSystem(OS.Linux);

        var result = hostSystem.EnsureShim("/opt/fgvm/fgvm");

        var failure = Assert.IsType<Result<Unit, ShimError>.Failure>(result);
        Assert.Equal(new ShimError.PathConflict(shimPath), failure.Error);
        Assert.Equal("user script", File.ReadAllText(shimPath));
    }

    [Fact]
    public void CreateOrOverwriteSymbolicLink_WritesRootSymlink()
    {
        if (OperatingSystem.IsWindows())
        {
            return;
        }

        var targetPath = Path.Combine(_rootPath, "Godot.x86_64");
        Directory.CreateDirectory(_rootPath);
        File.WriteAllText(targetPath, "");
        var hostSystem = CreateHostSystem(OS.Linux);

        var result = hostSystem.CreateOrOverwriteShortcut(targetPath);

        Assert.IsType<Result<Unit, SymlinkError>.Success>(result);
        var symlink = new FileInfo(Path.Combine(_rootPath, "Godot"));
        Assert.Equal(targetPath, symlink.LinkTarget);
    }

    [Fact]
    public void CreateOrOverwriteSymbolicLink_OnMacOS_WritesAppSymlink()
    {
        if (OperatingSystem.IsWindows())
        {
            return;
        }

        var targetAppPath = Path.Combine(_rootPath, "installations", "4.3-stable-standard", "macos.universal", "Godot.app");
        var oldExecutablePath = Path.Combine(targetAppPath, "Contents", "MacOS", "Godot");
        Directory.CreateDirectory(targetAppPath);
        Directory.CreateDirectory(Path.GetDirectoryName(oldExecutablePath)!);
        File.WriteAllText(oldExecutablePath, "");
        File.CreateSymbolicLink(Path.Combine(_rootPath, "Godot"), oldExecutablePath);
        var hostSystem = CreateHostSystem(OS.MacOS);

        var result = hostSystem.CreateOrOverwriteShortcut(targetAppPath);

        Assert.IsType<Result<Unit, SymlinkError>.Success>(result);
        Assert.Equal(targetAppPath, new FileInfo(Path.Combine(_rootPath, "Godot.app")).LinkTarget);
        Assert.Null(new FileInfo(Path.Combine(_rootPath, "Godot")).LinkTarget);
    }

    [Fact]
    public void ResolveCurrentSymlinks_OnMacOS_UsesAppSymlink()
    {
        if (OperatingSystem.IsWindows())
        {
            return;
        }

        var targetAppPath = Path.Combine(_rootPath, "installations", "4.3-stable-standard", "macos.universal", "Godot.app");
        Directory.CreateDirectory(targetAppPath);
        Directory.CreateSymbolicLink(Path.Combine(_rootPath, "Godot.app"), targetAppPath);
        var hostSystem = CreateHostSystem(OS.MacOS);

        var result = hostSystem.ResolveCurrentSymlinks();

        var success = Assert.IsType<Result<SymlinkInfo, SymlinkError>.Success>(result);
        Assert.Equal(targetAppPath, success.Value.SymlinkPath);
    }

    private HostSystem CreateHostSystem(OS os) =>
        new(
            new SystemInfo(os, Architecture.X64),
            new TestPathService(_rootPath, os),
            NullLogger<HostSystem>.Instance);

    private sealed class TestPathService(string rootPath, OS os) : IPathService
    {
        public string RootPath => rootPath;

        public string ConfigPath => Path.Combine(RootPath, "fgvm.ini");

        public string ReleasesPath => Path.Combine(RootPath, "releases.json");

        public string InstallationsPath => Path.Combine(RootPath, "installations.json");

        public string InstallationsDirectoryPath => Path.Combine(RootPath, "installations");

        public string BinPath => Path.Combine(RootPath, "bin");

        public string ShimPath => os == OS.Windows
            ? Path.Combine(BinPath, "godot.cmd")
            : Path.Combine(BinPath, "godot");

        public string SymlinkPath => os == OS.Windows
            ? Path.Combine(RootPath, "Godot.exe")
            : Path.Combine(RootPath, "Godot");

        public string MacAppSymlinkPath => Path.Combine(RootPath, "Godot.app");
        public string WindowsShortcutPath => Path.Combine(RootPath, "Godot.url");

        public string LogPath => Path.Combine(RootPath, "fgvm.log");
    }
}
