<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <IsPackable>false</IsPackable>
        <RootNamespace>Fgvm.Tests.Fixtures</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <ProjectReference Include="..\Fgvm\Fgvm.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>
