using System.IO.Enumeration;
using Fgvm.Godot;
using Fgvm.Types;
using Microsoft.Extensions.Logging;

namespace Fgvm.Environment;

/// <summary>
///     Provides host OS and filesystem operations used by fgvm.
/// </summary>
public sealed record HostDirectoryEntry(string FullName, string Name, FileAttributes Attributes);

public interface IHostSystem
{
    /// <summary>
    ///     Gets the current host OS and architecture.
    /// </summary>
    SystemInfo SystemInfo { get; }

    /// <summary>
    ///     Creates or updates fgvm's stable command shim.
    /// </summary>
    /// <param name="fgvmExecutablePath">The fgvm executable path the shim should call.</param>
    /// <returns>Success, or a shim error describing why the shim could not be written.</returns>
    Result<Unit, ShimError> EnsureShim(string fgvmExecutablePath);

    /// <summary>
    ///     Creates or replaces fgvm's selected launch symlink for the supplied target.
    /// </summary>
    /// <param name="symlinkTargetPath">The executable or app bundle path to link to.</param>
    /// <returns>Success, or a symlink error describing why the link could not be created.</returns>
    Result<Unit, SymlinkError> CreateOrOverwriteShortcut(string symlinkTargetPath);

    /// <summary>
    ///     Removes fgvm-managed selected Godot symlinks.
    /// </summary>
    /// <returns>Success, or a symlink error describing why removal failed.</returns>
    Result<Unit, SymlinkError> RemoveSymbolicLinks();

    /// <summary>
    ///     Resolves the currently configured fgvm symlinks.
    /// </summary>
    /// <returns>Current symlink information, or a symlink error.</returns>
    Result<SymlinkInfo, SymlinkError> ResolveCurrentSymlinks();

    /// <summary>
    ///     Lists locally installed Godot versions.
    /// </summary>
    /// <returns>Installed release names, or a filesystem error.</returns>
    Result<string[], FileSystemError> ListInstallations();

    /// <summary>
    ///     Checks whether a file exists.
    /// </summary>
    Result<bool, FileOperationError> FileExists(string path);

    /// <summary>
    ///     Checks whether a directory exists.
    /// </summary>
    Result<bool, FileOperationError> DirectoryExists(string path);

    /// <summary>
    ///     Creates a directory if it does not exist.
    /// </summary>
    Result<Unit, FileOperationError> CreateDirectory(string path);

    /// <summary>
    ///     Reads all text from a file.
    /// </summary>
    Result<string, FileOperationError> ReadAllText(string path);

    /// <summary>
    ///     Opens a file for reading.
    /// </summary>
    Result<Stream, FileOperationError> OpenRead(string path, FileShare fileShare = FileShare.Read);

    /// <summary>
    ///     Writes all text to a file.
    /// </summary>
    Result<Unit, FileOperationError> WriteAllText(string path, string contents);

    /// <summary>
    ///     Moves a file.
    /// </summary>
    Result<Unit, FileOperationError> MoveFile(string sourcePath, string destinationPath, bool overwrite);

    /// <summary>
    ///     Deletes a file if it exists.
    /// </summary>
    Result<Unit, FileOperationError> DeleteFileIfExists(string path);

    /// <summary>
    ///     Deletes a directory if it exists.
    /// </summary>
    Result<Unit, FileOperationError> DeleteDirectoryIfExists(string path, bool recursive);

    /// <summary>
    ///     Enumerates immediate child directories.
    /// </summary>
    Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError> EnumerateDirectories(string path);

    /// <summary>
    ///     Gets a directory's creation time in UTC.
    /// </summary>
    Result<DateTimeOffset, FileOperationError> GetDirectoryCreatedAtUtc(string path);

    /// <summary>
    ///     Resolves a filesystem link target.
    /// </summary>
    Result<string?, FileOperationError> ResolveLinkTarget(string path, bool returnFinalTarget);
}

/// <summary>
///     A way to organize host OS file operations.
/// </summary>
public sealed class HostSystem(SystemInfo systemInfo, IPathService pathService, ILogger<HostSystem> logger) : IHostSystem
{
    private const string ShimMarker = "Generated by fgvm. Do not edit.";

    /// <inheritdoc />
    public SystemInfo SystemInfo { get; } = systemInfo;

    /// <inheritdoc />
    public Result<bool, FileOperationError> FileExists(string path)
    {
        try
        {
            _ = Path.GetFullPath(path);
            return new Result<bool, FileOperationError>.Success(File.Exists(path));
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<bool, FileOperationError> DirectoryExists(string path)
    {
        try
        {
            _ = Path.GetFullPath(path);
            return new Result<bool, FileOperationError>.Success(Directory.Exists(path));
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<bool, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<Unit, FileOperationError> CreateDirectory(string path)
    {
        try
        {
            Directory.CreateDirectory(path);
            return new Result<Unit, FileOperationError>.Success(Unit.Value);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<string, FileOperationError> ReadAllText(string path)
    {
        try
        {
            return new Result<string, FileOperationError>.Success(File.ReadAllText(path));
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<string, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<string, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<string, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<string, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<string, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<string, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<string, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<Stream, FileOperationError> OpenRead(string path, FileShare fileShare = FileShare.Read)
    {
        try
        {
            return new Result<Stream, FileOperationError>.Success(
                new FileStream(path, FileMode.Open, FileAccess.Read, fileShare));
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Stream, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<Stream, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<Stream, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<Stream, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<Stream, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<Stream, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<Stream, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<Unit, FileOperationError> WriteAllText(string path, string contents)
    {
        try
        {
            File.WriteAllText(path, contents);
            return new Result<Unit, FileOperationError>.Success(Unit.Value);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<Unit, FileOperationError> MoveFile(string sourcePath, string destinationPath, bool overwrite)
    {
        try
        {
            File.Move(sourcePath, destinationPath, overwrite);
            return new Result<Unit, FileOperationError>.Success(Unit.Value);
        }
        catch (FileNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(sourcePath));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(destinationPath));
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.PermissionDenied(destinationPath));
        }
        catch (PathTooLongException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(destinationPath));
        }
        catch (ArgumentException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(destinationPath));
        }
        catch (NotSupportedException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(destinationPath));
        }
        catch (IOException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.IoFailure(destinationPath));
        }
    }

    /// <inheritdoc />
    public Result<Unit, FileOperationError> DeleteFileIfExists(string path)
    {
        try
        {
            File.Delete(path);
            return new Result<Unit, FileOperationError>.Success(Unit.Value);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<Unit, FileOperationError> DeleteDirectoryIfExists(string path, bool recursive)
    {
        try
        {
            if (Directory.Exists(path))
            {
                Directory.Delete(path, recursive);
            }

            return new Result<Unit, FileOperationError>.Success(Unit.Value);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<Unit, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError> EnumerateDirectories(string path)
    {
        try
        {
            var directories = Directory.EnumerateDirectories(path)
                .Select(directory =>
                {
                    var info = new DirectoryInfo(directory);
                    return new HostDirectoryEntry(info.FullName, info.Name, info.Attributes);
                })
                .ToArray();

            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Success(directories);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<IReadOnlyList<HostDirectoryEntry>, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<DateTimeOffset, FileOperationError> GetDirectoryCreatedAtUtc(string path)
    {
        try
        {
            return new Result<DateTimeOffset, FileOperationError>.Success(Directory.GetCreationTimeUtc(path));
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<DateTimeOffset, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<DateTimeOffset, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<DateTimeOffset, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<DateTimeOffset, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<DateTimeOffset, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<DateTimeOffset, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<DateTimeOffset, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }

    /// <inheritdoc />
    public Result<string?, FileOperationError> ResolveLinkTarget(string path, bool returnFinalTarget)
    {
        try
        {
            return new Result<string?, FileOperationError>.Success(
                new FileInfo(path).ResolveLinkTarget(returnFinalTarget)?.FullName);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<string?, FileOperationError>.Failure(new FileOperationError.PermissionDenied(path));
        }
        catch (FileNotFoundException)
        {
            return new Result<string?, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<string?, FileOperationError>.Failure(new FileOperationError.NotFound(path));
        }
        catch (PathTooLongException)
        {
            return new Result<string?, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (ArgumentException)
        {
            return new Result<string?, FileOperationError>.Failure(new FileOperationError.InvalidPath(path));
        }
        catch (NotSupportedException)
        {
            return new Result<string?, FileOperationError>.Failure(new FileOperationError.UnsupportedPath(path));
        }
        catch (IOException)
        {
            return new Result<string?, FileOperationError>.Failure(new FileOperationError.IoFailure(path));
        }
    }


    /// <inheritdoc />
    public Result<Unit, ShimError> EnsureShim(string fgvmExecutablePath)
    {
        var shimPath = pathService.ShimPath;
        var newLine = System.Environment.NewLine;
        var escapedFgvmPath = fgvmExecutablePath.Replace("\"", SystemInfo.CurrentOS == OS.Windows ? "\"\"" : "\\\"");
        var shimContent = SystemInfo.CurrentOS == OS.Windows
            ? $"@echo off{newLine}REM {ShimMarker}{newLine}if \"%~1\"==\"\" ({newLine}  \"{escapedFgvmPath}\" godot{newLine}) else ({newLine}  \"{escapedFgvmPath}\" godot --args \"%*\"{newLine}){newLine}exit /b %ERRORLEVEL%{newLine}"
            : $"#!/usr/bin/env sh{newLine}# {ShimMarker}{newLine}if [ \"$#\" -eq 0 ]; then{newLine}  exec \"{escapedFgvmPath}\" godot{newLine}else{newLine}  exec \"{escapedFgvmPath}\" godot --args \"$*\"{newLine}fi{newLine}";

        try
        {
            Directory.CreateDirectory(pathService.BinPath);

            var oldBinGodotPath = Path.Combine(pathService.BinPath, "godot");
            var oldBinGodot = new FileInfo(oldBinGodotPath);
            if (!string.Equals(oldBinGodotPath, shimPath, StringComparison.Ordinal) &&
                oldBinGodot.LinkTarget is not null)
            {
                oldBinGodot.Delete();
            }

            var shim = new FileInfo(shimPath);
            if (shim.LinkTarget is not null)
            {
                shim.Delete();
            }
            else if (Directory.Exists(shimPath))
            {
                return new Result<Unit, ShimError>.Failure(new ShimError.PathConflict(shimPath));
            }
            else if (File.Exists(shimPath))
            {
                var existingContent = File.ReadAllText(shimPath);
                if (!existingContent.Contains(ShimMarker, StringComparison.Ordinal) &&
                    !string.Equals(existingContent, shimContent, StringComparison.Ordinal))
                {
                    return new Result<Unit, ShimError>.Failure(new ShimError.PathConflict(shimPath));
                }

                if (string.Equals(existingContent, shimContent, StringComparison.Ordinal))
                {
                    if (SystemInfo.CurrentOS != OS.Windows && !OperatingSystem.IsWindows())
                    {
                        File.SetUnixFileMode(
                            shimPath,
                            UnixFileMode.UserRead |
                            UnixFileMode.UserWrite |
                            UnixFileMode.UserExecute |
                            UnixFileMode.GroupRead |
                            UnixFileMode.GroupExecute |
                            UnixFileMode.OtherRead |
                            UnixFileMode.OtherExecute);
                    }

                    return new Result<Unit, ShimError>.Success(Unit.Value);
                }
            }

            File.WriteAllText(shimPath, shimContent);

            if (SystemInfo.CurrentOS != OS.Windows && !OperatingSystem.IsWindows())
            {
                File.SetUnixFileMode(
                    shimPath,
                    UnixFileMode.UserRead |
                    UnixFileMode.UserWrite |
                    UnixFileMode.UserExecute |
                    UnixFileMode.GroupRead |
                    UnixFileMode.GroupExecute |
                    UnixFileMode.OtherRead |
                    UnixFileMode.OtherExecute);
            }

            return new Result<Unit, ShimError>.Success(Unit.Value);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Unit, ShimError>.Failure(
                new ShimError.WriteFailed(new FileOperationError.PermissionDenied(shimPath)));
        }
        catch (FileNotFoundException)
        {
            return new Result<Unit, ShimError>.Failure(
                new ShimError.WriteFailed(new FileOperationError.NotFound(shimPath)));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<Unit, ShimError>.Failure(
                new ShimError.WriteFailed(new FileOperationError.NotFound(shimPath)));
        }
        catch (PathTooLongException)
        {
            return new Result<Unit, ShimError>.Failure(
                new ShimError.WriteFailed(new FileOperationError.InvalidPath(shimPath)));
        }
        catch (ArgumentException)
        {
            return new Result<Unit, ShimError>.Failure(
                new ShimError.WriteFailed(new FileOperationError.InvalidPath(shimPath)));
        }
        catch (NotSupportedException)
        {
            return new Result<Unit, ShimError>.Failure(
                new ShimError.WriteFailed(new FileOperationError.UnsupportedPath(shimPath)));
        }
        catch (IOException)
        {
            return new Result<Unit, ShimError>.Failure(
                new ShimError.WriteFailed(new FileOperationError.IoFailure(shimPath)));
        }
    }

    /// <inheritdoc />
    public Result<Unit, SymlinkError> CreateOrOverwriteShortcut(string symlinkTargetPath)
    {
        if (RemoveSymbolicLinks() is Result<Unit, SymlinkError>.Failure removeFailure)
        {
            return removeFailure;
        }

        switch (SystemInfo.CurrentOS)
        {
            case OS.Windows:
                try
                {
                    // Create a .url shortcut instead of a symbolic link to avoid requiring Developer Mode
                    using var writer = new StreamWriter(pathService.WindowsShortcutPath);
                    writer.WriteLine("[InternetShortcut]");
                    writer.WriteLine("URL=" + new Uri(symlinkTargetPath).AbsoluteUri);
                    writer.WriteLine("IconIndex=0");
                    writer.WriteLine("IconFile=" + symlinkTargetPath);
                }
                catch (UnauthorizedAccessException)
                {
                    return new Result<Unit, SymlinkError>.Failure(new SymlinkError.PermissionDenied());
                }
                catch (Exception ex) when (ex is IOException or ArgumentException or NotSupportedException)
                {
                    return new Result<Unit, SymlinkError>.Failure(
                        new SymlinkError.InvalidSymlink(pathService.WindowsShortcutPath, "Shortcut could not be created"));
                }

                return new Result<Unit, SymlinkError>.Success(Unit.Value);
            case OS.MacOS:
                try
                {
                    Directory.CreateSymbolicLink(pathService.MacAppSymlinkPath, symlinkTargetPath);
                }
                catch (UnauthorizedAccessException)
                {
                    return new Result<Unit, SymlinkError>.Failure(new SymlinkError.PermissionDenied());
                }

                break;

            case OS.Linux:
                try
                {
                    File.CreateSymbolicLink(pathService.SymlinkPath, symlinkTargetPath);
                }
                catch (UnauthorizedAccessException)
                {
                    return new Result<Unit, SymlinkError>.Failure(new SymlinkError.PermissionDenied());
                }

                break;

            // TODO: Untested but possibly works with Linux builds?
            case OS.FreeBSD:
            case OS.Unknown:
            default:
                logger.LogError("Unsupported OS: {OS}", SystemInfo.CurrentOS);
                return new Result<Unit, SymlinkError>.Failure(
                    new SymlinkError.UnsupportedOS(SystemInfo.CurrentOS.ToString()));
        }

        if (SystemInfo.CurrentOS == OS.MacOS && !IsSymbolicLinkValid(pathService.MacAppSymlinkPath))
        {
            return new Result<Unit, SymlinkError>.Failure(
                new SymlinkError.InvalidSymlink(pathService.MacAppSymlinkPath, "Symlink created but appears invalid"));
        }

        if (SystemInfo.CurrentOS != OS.MacOS && !IsSymbolicLinkValid(pathService.SymlinkPath))
        {
            return new Result<Unit, SymlinkError>.Failure(
                new SymlinkError.InvalidSymlink(pathService.SymlinkPath, "Symlink created but appears invalid"));
        }

        return new Result<Unit, SymlinkError>.Success(Unit.Value);
    }

    /// <inheritdoc />
    public Result<Unit, SymlinkError> RemoveSymbolicLinks()
    {
        if (SystemInfo.CurrentOS is OS.FreeBSD or OS.Unknown)
        {
            return new Result<Unit, SymlinkError>.Failure(
                new SymlinkError.UnsupportedOS(SystemInfo.CurrentOS.ToString()));
        }

        try
        {
            if (SystemInfo.CurrentOS == OS.Windows)
            {
                var urlPath = pathService.WindowsShortcutPath;
                if (File.Exists(urlPath))
                {
                    File.Delete(urlPath);
                }

                return new Result<Unit, SymlinkError>.Success(Unit.Value);
            }

            // ATTN: On macOS the behavior of #.Exists can be unreliable due to the differences in how symbolic links are handled on the filesystem.
            // This is possibly related to the fact that the .app is a symlink to a directory and not a file, so it is technically "neither."
            // Therefore, we need to check if it has the ReparsePoint attribute to see if it "truly" exists.
            var macAppSymlinkFileInfo = new FileInfo(pathService.MacAppSymlinkPath);
            if ((macAppSymlinkFileInfo.Attributes & FileAttributes.ReparsePoint) == FileAttributes.ReparsePoint)
            {
                macAppSymlinkFileInfo.Delete();
            }

            var symlinkFileInfo = new FileInfo(pathService.SymlinkPath);
            if (SystemInfo.CurrentOS == OS.MacOS && symlinkFileInfo.LinkTarget is not null)
            {
                symlinkFileInfo.Delete();
            }
            else if (SystemInfo.CurrentOS != OS.MacOS && File.Exists(pathService.SymlinkPath))
            {
                File.Delete(pathService.SymlinkPath);
            }

            return new Result<Unit, SymlinkError>.Success(Unit.Value);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<Unit, SymlinkError>.Failure(new SymlinkError.PermissionDenied());
        }
        catch (Exception ex) when (ex is IOException or ArgumentException or NotSupportedException)
        {
            return new Result<Unit, SymlinkError>.Failure(new SymlinkError.RemoveFailed(pathService.RootPath));
        }
    }

    /// <inheritdoc />
    public Result<SymlinkInfo, SymlinkError> ResolveCurrentSymlinks()
    {
        if (SystemInfo.CurrentOS == OS.MacOS)
        {
            var appFile = new FileInfo(pathService.MacAppSymlinkPath);
            if (appFile.LinkTarget is null)
            {
                logger.LogInformation("Ran `which` without version set");
                return new Result<SymlinkInfo, SymlinkError>.Failure(
                    new SymlinkError.NoVersionSet());
            }

            if (!IsSymbolicLinkValid(pathService.MacAppSymlinkPath))
            {
                return new Result<SymlinkInfo, SymlinkError>.Failure(
                    new SymlinkError.InvalidSymlink(pathService.MacAppSymlinkPath, appFile.LinkTarget));
            }

            logger.LogInformation("{MacAppSymlinkPath} is currently set to: {LinkTarget}", pathService.MacAppSymlinkPath,
                appFile.LinkTarget);
            return new Result<SymlinkInfo, SymlinkError>.Success(new SymlinkInfo(appFile.LinkTarget));
        }

        if (SystemInfo.CurrentOS == OS.Windows)
        {
            var urlPath = pathService.WindowsShortcutPath;

            try
            {
                if (!File.Exists(urlPath))
                {
                    return new Result<SymlinkInfo, SymlinkError>.Failure(new SymlinkError.NoVersionSet());
                }

                var urlLine = File.ReadLines(urlPath)
                    .FirstOrDefault(line => line.StartsWith("URL=", StringComparison.OrdinalIgnoreCase));

                if (urlLine is null ||
                    !Uri.TryCreate(urlLine["URL=".Length..], UriKind.Absolute, out var uri) ||
                    !uri.IsFile)
                {
                    return new Result<SymlinkInfo, SymlinkError>.Failure(
                        new SymlinkError.InvalidSymlink(urlPath, "Shortcut does not contain a valid file URL"));
                }

                return new Result<SymlinkInfo, SymlinkError>.Success(
                    new SymlinkInfo(uri.LocalPath));
            }

            catch (UnauthorizedAccessException)
            {
                return new Result<SymlinkInfo, SymlinkError>.Failure(new SymlinkError.PermissionDenied());
            }

            catch (Exception ex) when (ex is IOException or ArgumentException or NotSupportedException)
            {
                return new Result<SymlinkInfo, SymlinkError>.Failure(
                    new SymlinkError.InvalidSymlink(urlPath, "Shortcut could not be read"));
            }
        }

        var file = new FileInfo(pathService.SymlinkPath);
        if (file.LinkTarget is null)
        {
            logger.LogInformation("Ran `which` without version set");
            return new Result<SymlinkInfo, SymlinkError>.Failure(
                new SymlinkError.NoVersionSet());
        }

        if (!IsSymbolicLinkValid(pathService.SymlinkPath))
        {
            return new Result<SymlinkInfo, SymlinkError>.Failure(
                new SymlinkError.InvalidSymlink(pathService.SymlinkPath, file.LinkTarget));
        }

        logger.LogInformation("{SymlinkPath} is currently set to: {LinkTarget}", pathService.SymlinkPath, file.LinkTarget);
        return new Result<SymlinkInfo, SymlinkError>.Success(
            new SymlinkInfo(file.LinkTarget));
    }

    /// <inheritdoc />
    public Result<string[], FileSystemError> ListInstallations()
    {
        try
        {
            var installed = new FileSystemEnumerable<string>(
                pathService.RootPath,
                (ref entry) => entry.FileName.ToString())
            {
                ShouldIncludePredicate = (ref entry) =>
                    entry is { IsDirectory: true, FileName: not "bin", IsHidden: false }
            };

            var releases = installed
                .Select(Release.TryParse)
                .OfType<Release>()
                .OrderByDescending(release => release)
                .Select(release => release.ReleaseNameWithRuntime)
                .ToArray();

            return new Result<string[], FileSystemError>.Success(releases);
        }
        catch (UnauthorizedAccessException)
        {
            return new Result<string[], FileSystemError>.Failure(new FileSystemError.PermissionDenied(pathService.RootPath));
        }
        catch (DirectoryNotFoundException)
        {
            return new Result<string[], FileSystemError>.Failure(new FileSystemError.DirectoryNotFound(pathService.RootPath));
        }
        catch (Exception ex) when (ex is IOException)
        {
            return new Result<string[], FileSystemError>.Failure(new FileSystemError.EnumerationFailed(pathService.RootPath));
        }
        catch (Exception ex) when (ex is ArgumentException or NotSupportedException)
        {
            return new Result<string[], FileSystemError>.Failure(new FileSystemError.InvalidPath(pathService.RootPath));
        }
    }


    private static bool IsSymbolicLinkValid(string symlinkTargetPath)
    {
        var symlinkFileInfo = new FileInfo(symlinkTargetPath);

        // check if considered a symlink
        if ((symlinkFileInfo.Attributes & FileAttributes.ReparsePoint) != FileAttributes.ReparsePoint)
        {
            return false;
        }

        var linkTarget = symlinkFileInfo.ResolveLinkTarget(true);

        return linkTarget is not null &&
               (File.Exists(linkTarget.FullName) || Directory.Exists(linkTarget.FullName));
    }
}
